<?php
require_once dirname(__DIR__) . '/config.php'; require_once dirname(__DIR__) . '/functions.php'; require_once dirname(__DIR__) . '/db.php';
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { redirect(url('applications/create.php')); }
$statuses = ['draft', 'submitted', 'in_analysis', 'risk_review', 'committee_review', 'approved', 'approved_with_conditions', 'rejected', 'cancelled', 'disbursed']; $currencies = ['MDL', 'EUR', 'USD']; $priorities = ['normal', 'high', 'urgent']; $errors = []; $clients = []; $fixedClient = null;
$clientId = post_int('client_id'); $client = null; if ($clientId && $pdo instanceof PDO) { $s = $pdo->prepare('SELECT id, client_name, idno FROM clients WHERE id = ? AND deleted_at IS NULL'); $s->execute([$clientId]); $client = $s->fetch(); }
$application = ['client_id' => $clientId, 'application_date' => clean_input(post_value('application_date')), 'requested_amount' => clean_input(post_value('requested_amount')), 'currency' => clean_input(post_value('currency', 'MDL')), 'requested_term_months' => clean_input(post_value('requested_term_months')), 'credit_product' => nullable_input(post_value('credit_product')), 'credit_purpose' => clean_input(post_value('credit_purpose')), 'repayment_source' => nullable_input(post_value('repayment_source')), 'existing_exposure_amount' => clean_input(post_value('existing_exposure_amount', '0')), 'proposed_total_exposure_amount' => clean_input(post_value('proposed_total_exposure_amount', '0')), 'status' => clean_input(post_value('status', 'draft')), 'priority' => clean_input(post_value('priority', 'normal')), 'notes' => nullable_input(post_value('notes'))];
if (!$client) { $errors[] = 'Client is required and must exist.'; } if (!is_valid_date($application['application_date']) || $application['application_date'] === '') { $errors[] = 'Application date is required and must use YYYY-MM-DD format.'; } if (!is_numeric($application['requested_amount']) || (float) $application['requested_amount'] <= 0) { $errors[] = 'Requested amount must be greater than 0.'; } if (!in_array($application['currency'], $currencies, true)) { $errors[] = 'Invalid currency.'; } if (!ctype_digit((string) $application['requested_term_months']) || (int) $application['requested_term_months'] <= 0) { $errors[] = 'Requested term must be greater than 0.'; } if ($application['credit_purpose'] === '') { $errors[] = 'Credit purpose is required.'; } if (!is_numeric($application['existing_exposure_amount']) || (float) $application['existing_exposure_amount'] < 0) { $errors[] = 'Existing exposure amount cannot be negative.'; } if (!is_numeric($application['proposed_total_exposure_amount']) || (float) $application['proposed_total_exposure_amount'] < 0) { $errors[] = 'Proposed total exposure amount cannot be negative.'; } if (!in_array($application['status'], $statuses, true)) { $errors[] = 'Invalid application status.'; } if (!in_array($application['priority'], $priorities, true)) { $errors[] = 'Invalid priority.'; }
if ($errors || !$pdo instanceof PDO) { $currentSection = 'applications'; $pageTitle = 'Create application'; if ($pdo instanceof PDO) { $s = $pdo->prepare('SELECT id, client_name, idno FROM clients WHERE deleted_at IS NULL ORDER BY client_name'); $s->execute(); $clients = $s->fetchAll(); if ($client) { $fixedClient = $client; } } require_once dirname(__DIR__) . '/header.php'; require_once dirname(__DIR__) . '/sidebar.php'; ?><section class="page-heading mb-4"><p class="eyebrow mb-2">Application registry</p><h1 class="h2 mb-0">Create new application</h1></section><div class="card border-0 shadow-sm"><div class="card-body p-4"><form method="post" action="<?= e(url('applications/store.php')) ?>" class="row g-3"><?php require __DIR__ . '/_form.php'; ?><div class="col-12"><button class="btn btn-primary" type="submit">Save application</button></div></form></div></div><?php require_once dirname(__DIR__) . '/footer.php'; exit; }
$year = date('Y'); $s = $pdo->prepare('SELECT application_number FROM credit_applications WHERE application_number LIKE ? ORDER BY application_number DESC LIMIT 1'); $s->execute(['APP-' . $year . '-%']); $last = $s->fetchColumn(); $next = $last ? ((int) substr($last, -4) + 1) : 1; $applicationNumber = 'APP-' . $year . '-' . str_pad((string) $next, 4, '0', STR_PAD_LEFT);
$data = $application; $data['application_number'] = $applicationNumber; $data['requested_amount'] = (float) $data['requested_amount']; $data['requested_term_months'] = (int) $data['requested_term_months']; $data['existing_exposure_amount'] = (float) $data['existing_exposure_amount']; $data['proposed_total_exposure_amount'] = (float) $data['proposed_total_exposure_amount'];
$s = $pdo->prepare('INSERT INTO credit_applications (client_id, application_number, application_date, requested_amount, currency, requested_term_months, credit_product, credit_purpose, repayment_source, existing_exposure_amount, proposed_total_exposure_amount, status, priority, notes) VALUES (:client_id, :application_number, :application_date, :requested_amount, :currency, :requested_term_months, :credit_product, :credit_purpose, :repayment_source, :existing_exposure_amount, :proposed_total_exposure_amount, :status, :priority, :notes)'); $s->execute($data); $id = (int) $pdo->lastInsertId(); log_action($pdo, 'create application', 'application', $id, null, $data); redirect(url('applications/view.php?id=' . $id));
