<?php
require_once dirname(__DIR__) . '/config.php'; require_once dirname(__DIR__) . '/functions.php'; require_once dirname(__DIR__) . '/db.php';
$currentSection = 'applications'; $pageTitle = 'Application card'; $id = get_int_param('id'); $application = null; $client = null; $comments = [];
if ($id && $pdo instanceof PDO) { $s = $pdo->prepare('SELECT ca.*, c.client_name, c.idno, c.legal_form, c.activity_sector, c.status AS client_status FROM credit_applications ca INNER JOIN clients c ON c.id = ca.client_id WHERE ca.id = ? AND ca.deleted_at IS NULL'); $s->execute([$id]); $application = $s->fetch(); if ($application) { $client = ['id' => $application['client_id'], 'client_name' => $application['client_name'], 'idno' => $application['idno'], 'legal_form' => $application['legal_form'], 'activity_sector' => $application['activity_sector'], 'status' => $application['client_status']]; $s = $pdo->prepare('SELECT * FROM application_comments WHERE application_id = ? AND deleted_at IS NULL ORDER BY created_at DESC, id DESC'); $s->execute([$id]); $comments = $s->fetchAll(); } }
require_once dirname(__DIR__) . '/header.php'; require_once dirname(__DIR__) . '/sidebar.php';
if (!$application) { render_error_page('Application not found', 'The requested application does not exist or was archived.', url('applications/index.php'), 'Back to applications list'); require_once dirname(__DIR__) . '/footer.php'; exit; }
?>
<section class="page-heading mb-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3"><div><p class="eyebrow mb-2">Application card</p><h1 class="h2 mb-1"><?= e($application['application_number']) ?></h1><p class="text-secondary mb-0"><?= e($application['client_name']) ?> · <?= e($application['status']) ?></p></div><div class="align-self-lg-center d-flex gap-2"><a class="btn btn-primary" href="<?= e(url('applications/edit.php?id=' . $application['id'])) ?>">Edit application</a><a class="btn btn-outline-secondary" href="<?= e(url('applications/index.php')) ?>">Back to applications list</a><a class="btn btn-outline-primary" href="<?= e(url('clients/view.php?id=' . $application['client_id'])) ?>">Back to client card</a></div></div></section>
<div class="row g-4 mb-4"><div class="col-lg-8"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Main application data</h2><div class="row g-3"><?php foreach (['Application number' => $application['application_number'], 'Application date' => format_date($application['application_date']), 'Client name' => $application['client_name'], 'Requested amount' => format_amount($application['requested_amount'], $application['currency']), 'Currency' => $application['currency'], 'Requested term' => $application['requested_term_months'] . ' months', 'Credit product' => $application['credit_product'], 'Credit purpose' => $application['credit_purpose'], 'Repayment source' => $application['repayment_source'], 'Existing exposure amount' => format_amount($application['existing_exposure_amount'], $application['currency']), 'Proposed total exposure amount' => format_amount($application['proposed_total_exposure_amount'], $application['currency']), 'Status' => $application['status'], 'Priority' => $application['priority'], 'Notes' => $application['notes']] as $label => $value): ?><div class="col-md-6"><div class="text-secondary small"><?= e($label) ?></div><div class="fw-semibold"><?= e($value ?: '-') ?></div></div><?php endforeach; ?></div></div></div></div><div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Client summary</h2><?php foreach (['Client name' => $client['client_name'], 'IDNO' => $client['idno'], 'Legal form' => $client['legal_form'], 'Activity sector' => $client['activity_sector'], 'Status' => $client['status']] as $label => $value): ?><div class="mb-3"><div class="text-secondary small"><?= e($label) ?></div><div class="fw-semibold"><?= e($value ?: '-') ?></div></div><?php endforeach; ?><a class="btn btn-outline-primary" href="<?= e(url('clients/view.php?id=' . $client['id'])) ?>">Open client card</a></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Application comments</h2><form method="post" action="<?= e(url('applications/comment_store.php')) ?>" class="mb-4"><input type="hidden" name="application_id" value="<?= e($application['id']) ?>"><label class="form-label" for="comment_text">Comment text</label><textarea class="form-control mb-2" id="comment_text" name="comment_text" rows="3" required></textarea><button class="btn btn-primary" type="submit">Add comment</button></form><div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>Comment text</th><th>Created date</th><th class="text-end">Action</th></tr></thead><tbody><?php if (!$comments): ?><tr><td colspan="3" class="text-center text-secondary py-3">No comments.</td></tr><?php endif; ?><?php foreach ($comments as $comment): ?><tr><td><?= e($comment['comment_text']) ?></td><td><?= e(format_date($comment['created_at'], 'd.m.Y H:i')) ?></td><td class="text-end"><a class="btn btn-sm btn-outline-danger" href="<?= e(url('applications/comment_delete.php?id=' . $comment['id'])) ?>" onclick="return confirm('Delete this comment?');">Delete</a></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<div class="row g-3"><?php foreach (['Financial statements', 'Financial ratios', 'Collateral', 'Scoring', 'Credit memo', 'Committee decision'] as $module): ?><div class="col-md-4"><div class="card module-placeholder border-0 shadow-sm h-100"><div class="card-body"><h3 class="h6 mb-2"><?= e($module) ?></h3><p class="text-secondary mb-0">This module will be implemented in the next development stages.</p></div></div></div><?php endforeach; ?></div>
<?php require_once dirname(__DIR__) . '/footer.php'; ?>
