<?php
require_once dirname(__DIR__) . '/config.php'; require_once dirname(__DIR__) . '/functions.php'; require_once dirname(__DIR__) . '/db.php';
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { redirect(url('clients/index.php')); }
$partyTypes = ['individual', 'legal_entity']; $relationshipTypes = ['shareholder', 'beneficial_owner', 'administrator', 'group_company', 'guarantor', 'other']; $errors = [];
$clientId = post_int('client_id'); $client = null;
if ($clientId && $pdo instanceof PDO) { $s = $pdo->prepare('SELECT * FROM clients WHERE id = ? AND deleted_at IS NULL'); $s->execute([$clientId]); $client = $s->fetch(); }
$ownership = nullable_input(post_value('ownership_percent'));
$party = ['client_id' => $clientId, 'party_name' => clean_input(post_value('party_name')), 'party_type' => clean_input(post_value('party_type', 'individual')), 'idno_or_idnp' => nullable_input(post_value('idno_or_idnp')), 'relationship_type' => clean_input(post_value('relationship_type', 'other')), 'ownership_percent' => $ownership, 'is_beneficiary' => isset($_POST['is_beneficiary']) ? 1 : 0, 'notes' => nullable_input(post_value('notes'))];
if (!$client) { $errors[] = 'Client not found.'; } if ($party['party_name'] === '') { $errors[] = 'Party name is required.'; } if (!in_array($party['party_type'], $partyTypes, true)) { $errors[] = 'Invalid party type.'; } if (!in_array($party['relationship_type'], $relationshipTypes, true)) { $errors[] = 'Invalid relationship type.'; } if ($ownership !== null && (!is_numeric($ownership) || (float) $ownership < 0 || (float) $ownership > 100)) { $errors[] = 'Ownership percent must be between 0 and 100.'; }
if ($errors) { $currentSection = 'clients'; $pageTitle = 'Add related party'; require_once dirname(__DIR__) . '/header.php'; require_once dirname(__DIR__) . '/sidebar.php'; ?><section class="page-heading mb-4"><p class="eyebrow mb-2">Related parties</p><h1 class="h2 mb-0">Add related party</h1></section><div class="card border-0 shadow-sm"><div class="card-body p-4"><form class="row g-3" method="post" action="<?= e(url('clients/related_party_store.php')) ?>"><?php require __DIR__ . '/_related_party_form.php'; ?><div class="col-12"><button class="btn btn-primary" type="submit">Save related party</button></div></form></div></div><?php require_once dirname(__DIR__) . '/footer.php'; exit; }
$party['ownership_percent'] = $ownership === null ? null : (float) $ownership;
$s = $pdo->prepare('INSERT INTO client_related_parties (client_id, party_name, party_type, idno_or_idnp, relationship_type, ownership_percent, is_beneficiary, notes) VALUES (:client_id, :party_name, :party_type, :idno_or_idnp, :relationship_type, :ownership_percent, :is_beneficiary, :notes)'); $s->execute($party); $id = (int) $pdo->lastInsertId(); log_action($pdo, 'create related party', 'related_party', $id, null, $party); redirect(url('clients/view.php?id=' . $clientId));
