<?php
require_once dirname(__DIR__) . '/config.php';
require_once dirname(__DIR__) . '/functions.php';
require_once dirname(__DIR__) . '/db.php';
$currentSection = 'financials'; $pageTitle = 'Financial period'; $id = get_int_param('id'); $period = null; $balance = null; $income = null; $ratio = null;
$assetFields = ['cash_and_equivalents'=>'Cash and equivalents','accounts_receivable'=>'Accounts receivable','inventory'=>'Inventory','other_current_assets'=>'Other current assets','total_current_assets'=>'Total current assets','fixed_assets'=>'Fixed assets','other_non_current_assets'=>'Other non-current assets','total_non_current_assets'=>'Total non-current assets','total_assets'=>'Total assets'];
$liabilityFields = ['short_term_debt'=>'Short-term debt','accounts_payable'=>'Accounts payable','other_current_liabilities'=>'Other current liabilities','total_current_liabilities'=>'Total current liabilities','long_term_debt'=>'Long-term debt','other_non_current_liabilities'=>'Other non-current liabilities','total_non_current_liabilities'=>'Total non-current liabilities','equity'=>'Equity','total_liabilities_and_equity'=>'Total liabilities and equity'];
$incomeFields = ['revenue'=>'Revenue','cost_of_goods_sold'=>'Cost of goods sold','gross_profit'=>'Gross profit','operating_expenses'=>'Operating expenses','ebitda'=>'EBITDA','depreciation_amortization'=>'Depreciation and amortization','ebit'=>'EBIT','interest_expense'=>'Interest expense','profit_before_tax'=>'Profit before tax','tax_expense'=>'Tax expense','net_profit'=>'Net profit'];
$calculatedBalanceFields = ['total_current_assets','total_non_current_assets','total_assets','total_current_liabilities','total_non_current_liabilities','total_liabilities_and_equity'];
$calculatedIncomeFields = ['gross_profit','ebitda','ebit','profit_before_tax','net_profit'];
if ($id && $pdo instanceof PDO) {
    $s = $pdo->prepare('SELECT fp.*, ca.application_number, ca.requested_amount, ca.currency, ca.status, ca.client_id, ca.interest_rate, ca.annual_debt_service_amount, c.client_name, c.idno FROM financial_periods fp INNER JOIN credit_applications ca ON ca.id = fp.application_id INNER JOIN clients c ON c.id = ca.client_id WHERE fp.id = ? AND fp.deleted_at IS NULL'); $s->execute([$id]); $period = $s->fetch();
    if ($period) { $s = $pdo->prepare('SELECT * FROM financial_balance_sheet WHERE financial_period_id = ?'); $s->execute([$id]); $balance = $s->fetch(); $s = $pdo->prepare('SELECT * FROM financial_income_statement WHERE financial_period_id = ?'); $s->execute([$id]); $income = $s->fetch(); $s = $pdo->prepare('SELECT * FROM financial_ratios WHERE financial_period_id = ? LIMIT 1'); $s->execute([$id]); $ratio = $s->fetch(); }
}
require_once dirname(__DIR__) . '/header.php'; require_once dirname(__DIR__) . '/sidebar.php';
if (!$period) { render_error_page('Financial period not found', 'The requested financial period does not exist or was deleted.', url('financials/index.php'), 'Back to financial statements'); require_once dirname(__DIR__) . '/footer.php'; exit; }
$rawBalance = $balance;
$balance = $balance ? calculate_balance_sheet_totals($balance) : null;
$income = $income ? calculate_income_statement_totals($income) : null;
$balanceDiff = $balance ? balance_difference($balance['total_assets'], $balance['total_liabilities_and_equity']) : 0.0;
$hasOldZeroTotals = $rawBalance && abs(decimal_value($rawBalance['total_assets'] ?? 0)) <= 0.01 && abs(decimal_value($rawBalance['total_liabilities_and_equity'] ?? 0)) <= 0.01 && has_nonzero_balance_base_values($rawBalance);
$isBalanced = $balance && abs($balanceDiff) <= 0.01;
$incomeIssues = $income ? check_income_statement_consistency($income) : [];
?>
<section class="page-heading mb-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3"><div><p class="eyebrow mb-2">Financial statements</p><h1 class="h2 mb-1"><?= e($period['period_label']) ?></h1><p class="text-secondary mb-0"><?= e($period['application_number']) ?> · <?= e($period['client_name']) ?></p></div><div class="align-self-lg-center d-flex gap-2 flex-wrap"><a class="btn btn-primary" href="<?= e(url('financials/edit_period.php?id=' . $period['id'])) ?>">Edit period</a><a class="btn btn-outline-secondary" href="<?= e(url('financials/edit_balance.php?id=' . $period['id'])) ?>">Edit balance sheet</a><a class="btn btn-outline-secondary" href="<?= e(url('financials/edit_income.php?id=' . $period['id'])) ?>">Edit income statement</a></div></div></section>
<div class="row g-4 mb-4">
    <div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Application information</h2><div class="row g-3"><?php foreach (['Application number'=>$period['application_number'],'Client name'=>$period['client_name'],'IDNO'=>$period['idno'],'Requested amount'=>format_amount($period['requested_amount'], $period['currency']),'Currency'=>$period['currency'],'Annual interest rate'=>format_interest_rate($period['interest_rate'] ?? null),'Estimated new loan annual debt service'=>(($period['annual_debt_service_amount'] ?? null) === null || ($period['annual_debt_service_amount'] ?? '') === '' ? 'N/A' : format_amount($period['annual_debt_service_amount'], $period['currency'])),'Status'=>$period['status']] as $label=>$value): ?><div class="col-md-6"><div class="text-secondary small"><?= e($label) ?></div><div class="fw-semibold"><?= e($value ?: '-') ?></div></div><?php endforeach; ?></div><div class="mt-3 d-flex gap-2"><a class="btn btn-sm btn-outline-primary" href="<?= e(url('applications/view.php?id=' . $period['application_id'])) ?>">Open application</a><a class="btn btn-sm btn-outline-primary" href="<?= e(url('clients/view.php?id=' . $period['client_id'])) ?>">Open client</a></div></div></div></div>
    <div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Period information</h2><div class="row g-3"><?php foreach (['Period label'=>$period['period_label'],'Period type'=>$period['period_type'],'Period end date'=>format_date($period['period_end_date']),'Is audited'=>$period['is_audited'] ? 'Yes' : 'No','Data source'=>$period['data_source'],'Notes'=>$period['notes']] as $label=>$value): ?><div class="col-md-6"><div class="text-secondary small"><?= e($label) ?></div><div class="fw-semibold"><?= e($value ?: '-') ?></div></div><?php endforeach; ?></div></div></div></div>
</div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Balance sheet</h2><span class="badge <?= $isBalanced ? 'text-bg-success' : 'text-bg-danger' ?>"><?= e($isBalanced ? 'Balanced' : 'Not balanced') ?></span></div><?php if (!$isBalanced): ?><div class="alert alert-warning">Balance difference after automatic recalculation: <?= e(format_amount($balanceDiff, '')) ?><?php if ($hasOldZeroTotals): ?> Old saved total rows are zero while base rows are not zero; save the balance sheet to persist recalculated totals.<?php endif; ?></div><?php endif; ?><div class="row g-4"><div class="col-lg-6"><h3 class="h6">Assets</h3><table class="table table-sm"><tbody><?php foreach ($assetFields as $field=>$label): ?><tr class="<?= in_array($field, $calculatedBalanceFields, true) ? 'table-light fw-semibold' : '' ?>"><th><?= e($label) ?><?php if (in_array($field, $calculatedBalanceFields, true)): ?> <span class="badge text-bg-light">Calculated</span><?php endif; ?></th><td class="text-end"><?= e(format_amount($balance[$field] ?? 0, '')) ?></td></tr><?php endforeach; ?></tbody></table></div><div class="col-lg-6"><h3 class="h6">Liabilities and equity</h3><table class="table table-sm"><tbody><?php foreach ($liabilityFields as $field=>$label): ?><tr class="<?= in_array($field, $calculatedBalanceFields, true) ? 'table-light fw-semibold' : '' ?>"><th><?= e($label) ?><?php if (in_array($field, $calculatedBalanceFields, true)): ?> <span class="badge text-bg-light">Calculated</span><?php endif; ?></th><td class="text-end"><?= e(format_amount($balance[$field] ?? 0, '')) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Income statement</h2><span class="badge <?= !$incomeIssues ? 'text-bg-success' : 'text-bg-warning' ?>"><?= e(!$incomeIssues ? 'Controls passed' : 'Review warnings') ?></span></div><?php if ($incomeIssues): ?><div class="alert alert-warning"><strong>P&amp;L discrepancies found:</strong><ul class="mb-0"><?php foreach ($incomeIssues as $issue): ?><li><?= e($issue['label']) ?>; difference: <?= e(format_amount($issue['difference'], '')) ?></li><?php endforeach; ?></ul></div><?php endif; ?><table class="table table-sm"><tbody><?php foreach ($incomeFields as $field=>$label): ?><tr class="<?= in_array($field, $calculatedIncomeFields, true) ? 'table-light fw-semibold' : '' ?>"><th><?= e($label) ?><?php if (in_array($field, $calculatedIncomeFields, true)): ?> <span class="badge text-bg-light">Calculated</span><?php endif; ?></th><td class="text-end"><?= e(format_amount($income[$field] ?? 0, '')) ?></td></tr><?php endforeach; ?></tbody></table></div></div>

<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-3"><div><h2 class="h5 mb-1">Financial ratios</h2><p class="text-secondary small mb-0">Analytical indicators calculated from the entered balance sheet and income statement. For MVP, DSCR is calculated as EBITDA divided by the estimated annual debt service amount for the requested loan.</p></div><div class="d-flex gap-2 flex-wrap"><form method="post" action="<?= e(url('ratios/calculate.php')) ?>"><input type="hidden" name="financial_period_id" value="<?= e($period['id']) ?>"><button class="btn btn-primary" type="submit"><?= e($ratio ? 'Recalculate ratios' : 'Calculate ratios') ?></button></form><?php if ($ratio): ?><a class="btn btn-outline-primary" href="<?= e(url('ratios/view.php?financial_period_id=' . $period['id'])) ?>">Open detailed ratios</a><?php endif; ?></div></div><?php if (!$ratio): ?><div class="alert alert-warning mb-0">Financial ratios have not been calculated yet.</div><?php else: ?><div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>Ratio</th><th>Value</th><th>Interpretation</th></tr></thead><tbody><?php foreach (ratio_definitions() as $group): ?><tr class="table-secondary"><th colspan="3"><?= e($group['label']) ?></th></tr><?php foreach ($group['ratios'] as $key => $definition): ?><tr><td><?= e($definition['label']) ?></td><td><?= e(format_ratio($ratio[$key] ?? null, $definition['percent'])) ?></td><td><?= e(interpret_ratio($key, $ratio[$key] ?? null, ['equity' => $balance['equity'] ?? null])) ?></td></tr><?php endforeach; ?><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">Quick actions</h2><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-primary" href="<?= e(url('financials/edit_period.php?id=' . $period['id'])) ?>">Edit period</a><a class="btn btn-outline-primary" href="<?= e(url('financials/edit_balance.php?id=' . $period['id'])) ?>">Edit balance sheet</a><a class="btn btn-outline-primary" href="<?= e(url('financials/edit_income.php?id=' . $period['id'])) ?>">Edit income statement</a><a class="btn btn-outline-secondary" href="<?= e(url('applications/view.php?id=' . $period['application_id'])) ?>">Back to application</a><a class="btn btn-outline-secondary" href="<?= e(url('financials/index.php')) ?>">Back to financial statements list</a></div></div></div>
<?php require_once dirname(__DIR__) . '/footer.php'; ?>
